# baseurl: /tufte-jekyll
title: Matthew J Michalska-Smith's Personal Blog
author: Matthew J Michalska-Smith
#description:
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/New_York
excerpt_separator: <!--more-->
exclude: ['Gemfile', 'Gemfile.lock', 'node_modules', '_drafts', 'Code']
plugins_dir: ['github-pages']
github: [metadata]
